title: "Henry Wolf"
description: "Personal website & thoughts on data, AI, and adventures."
url: "https://henrywolf.ai"
baseurl: ""
author:
  name: "Henry Wolf"
  email: "henry@henrywolf.ai"
social_links:
  linkedin: "https://www.linkedin.com/in/henrywolfai"
  resume:   "/assets/docs/Wolf_2025.pdf"
  scholar:  "https://scholar.google.com/citations?user=Q1sWJpsAAAAJ"
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
